### ISSUE TITLE
Munit issue with Mule 3.6.0 mule-module-spring-config

### ISSUE THREAD

**Issue by jpendle** [mulesoft/munit#154]
When I run my Munit tests using Mule 3.6.0 dependencies, I get the following error:
```
java.lang.RuntimeException: org.mule.api.config.ConfigurationException: Unexpected exception parsing XML document from URL [jar:file:/PATH-TO-JAR/mule-module-spring-config-3.6.0.jar!/registry-bootstrap-mule-config.xml]; nested exception is java.lang.NoSuchMethodError: org.mule.config.spring.MuleHierarchicalBeanDefinitionParserDelegate.<init>(Lorg/springframework/beans/factory/xml/XmlReaderContext;Lorg/springframework/beans/factory/xml/DefaultBeanDefinitionDocumentReader;)V (org.mule.api.lifecycle.InitialisationException)
```
If I switch to the 3.5.0 version of the `mule-module-spring-config` dependency it works fine, and I can easily do this when running my tests with Maven. However, when running them in Anypoint Studio I have to change the whole runtime version to 3.5.0 in order to run my tests.

**Comment by damiansima** [comment]
Hi @jpendle 

Yes you're correct. 
You see Munit needs to change with each version Mule ESB. That's why we have versions for each Mule runtime.

We are currently working in the new version of Munit that will support Mule 3.6.0 but it's not quite ready yet.

I'll let you guys know when it is ready ;)

Cheers!
