### ISSUE TITLE
MEL expressions evaluated twice with Munit?

### ISSUE THREAD

**Issue by jpendle** [mulesoft/munit#157]
I have some Mule code which includes the following bit of MEL which grabs the next element from an Iterator and invokes some method on it:

`"#[payload.next().someMethod()]"`

This works fine using the normal Mule runtime. However, when this expression gets executed as part of an Munit test, it isn't working. I've put a breakpoint on the `next()` method and it seems it gets invoked twice during an Munit run, but as there is only 1 element in the collection I am iterating over, the second call of `next()` fails. 

Is it indeed something happening with Munit that causes this behaviour? I'm using 3.5-M3. Looking at the Stack trace on the breakpoint, it looks like the `MunitMessageProcessorInterceptor` class might be causing the additional evaluation of the expression (specifically, the `AbstractMessageProcessorInterceptor.evaluate()` method).

**Comment by damiansima** [comment]
Hi @jpendle 

You're correct I'll open a Jira and I'll take a look at it.

**Comment by damiansima** [comment]
Hi @jpendle

You are correct, but what you're experiencing is a side effect, please let me explain .

You see Munit provides you the ability to create mocks, spies, etc and to so by matching patterns. 
That is you can, for instance, create a mock for a MP when an attribute of that MP matches a certain value, lets say you have:
```

	<set-variable variableName="my_var" value="#[payload]" doc:name="Variable"/>
```

You can very well create the following mock:
```

 	<mock:when messageProcessor="set-variable">
 		<mock:with-attributes>
			<mock:with-attribute name="value" whereValue-ref="#['1']"/>
		</mock:with-attributes>
        <mock:then-return payload-ref="#[payload]"/>
    </mock:when> 
```

In this case the mock will be created, if an only if, the payload of the message when reaching the set-variable MP is "1".

The only way we have to achieve this is by evaluating the expression in the MP before we can check if we need to apply a mock (regardless if there's a mock for that MP).
Sadly we'll have not better way to do it (and I don't see us having one in the near future).

On the other hand, we can do some stuff to protect the message, in fact I've implemented some of those thanks to your bug. 
For instance, we can stop this evaluation from affecting the Mule event. Let's say the expression tries to set a value in a flow var, then we can revert that.
But we can not protect you payload.

Now in your example, it turns out the expression is altering the internal state of the payload. 
Same happens with the enricher scope, when running normaly, it protects the message but if you alter the internal state of payload there's not much we can do.

I reckon we should do a better work documenting this, and we'll do it. But I'm sorry to say that, this is a limitation of Munit and for now there's nothing we can do. 

Any way, knowing this, in your scenario I will sugest that you alter you application a bit. 
For instance, the for each scope is there just for scenarios like the one you're describing, i.e. iterate over a list and take actions. 

Cheers

**Comment by jpendle** [comment]
Thanks @damiansima for the thorough explanation, it's good to get a better understanding of exactly what's going on :)
