### ISSUE TITLE
What is the use of Mock 

### ISSUE THREAD

**Issue by utsavvishnoi** [mulesoft/munit#159]
Hi i am newbee to MUnit and just want to know that what is the use of Mock and Mock Endpoint and how to use this and when to use this?

**Comment by damiansima** [comment]
Hi @utsavvishnoi 

By mock I reckon you are talking about the mock MP, in that case you could check:
https://github.com/mulesoft/munit/wiki/defining-mocks

Basically a mock allows you to instead of executing the actual MP have Munit to intercept that and return a predefined payload/trhow an exception/etc.

Regarding the mock endpoints, Munit by default disable the inbound endpoint in order to stop external calls to possibly tamper with the run of your Munit test. You can re enable them if you find you want do to an integration test or validate something else, if you have a specific scenario you want to try we can discuss further. 

Cheers!
