### ISSUE TITLE
how to mock database connector in java (and mule)

### ISSUE THREAD

**Issue by jasonchw** [mulesoft/munit#163]
Hi there,

I have a sub-flow using database connector, like the following code snippet,
```
<sub-flow name="subFlow" doc:name="subFlow">
    <db:select config-ref="dbConnector" doc:name="Database">
        <db:parameterized-query><![CDATA[
            SELECT 'FIRST', 'LAST' FROM DUAL
        ]]></db:parameterized-query>
    </db:select>
    <set-payload value="#[payload[0]]" doc:name="Set Payload" />
    <logger level="INFO" message="#[message.id] - #[payload]" doc:name="Logger" />
</sub-flow>
```
can you tell me how can I mock it in java (and mule)?

Thanks,
Jason

**Comment by damiansima** [comment]
Hi @jasonchw, 

Not sure if you have checked other threads but just in case, db  connector mocking works since 3.5-M3-SNAPSHOT. So please use that version if you intend to do this.

That said, the DB connector is like any other connector so you just need to provide namespace, MP name, and if needed a particular attribute, and that's it.
Here is a quick example:

**Production Code**
```
<flow name="yourFlow">
  <db:select config-ref="MySQL_Configuration" doc:name="Database">
    <db:parameterized-query><![CDATA[SELECT * FROM TABLE]]></db:parameterized-query>
  </db:select>
</flow>
```
**Test Code**
```java
public class ElTest extends FunctionalMunitSuite {

	@Override
	protected String getConfigResources() {
		return "your_file.xml";
	}

	@Test
	public void atest() throws MuleException, Exception {
		String mockedPayload = "some random payload";
		whenMessageProcessor("select").ofNamespace("db").thenReturn(muleMessageWithPayload(mockedPayload));

		MuleEvent event = runFlow("yourFlow", testEvent(""));

		assertEquals("The payload returned is not as expected!", mockedPayload, event.getMessage().getPayload());
	}

}
```

Please bear in mind that the DB connector select will return a list as payload, this is just for the example purposes. 


Cheers!

**Comment by cchilukoori** [comment]
Can you provide the example in Mule for mocking new database connector please?

**Comment by damiansima** [comment]
Hi @cchilukoori ,

Sure please check, https://github.com/mulesoft/munit/blob/munit-3.5.x/munit-integration-tests/src/test/munit/db-connector-test.xml

I  still have to check your last issue #160, I just didn't want to answer it in parts I'll circle back to it though
