### ISSUE TITLE
Can MUnit 3.5-M* work with Mule Server 3.4.0?

### ISSUE THREAD

**Issue by jcbusta** [mulesoft/munit#164]
I was wondering if the major.minor version (3.4 and 3.5 etc.) of munit is directly dependent to work with the equivalent version of the Mule server. Ie. Can I use MUnit 3.5 with Mule Server 3.4.0?

Thanks,

Juan

**Comment by damiansima** [comment]
Hi @jcbusta 

There is a dependency between Munit and Mule core, and yes **IDEALY** you should be using the Munit version that matches the Mule core version.

You certainly **can not*** do Munit v3.5.x and Mule core v3.6.x, because that won't work.

Then again for the most part Munit is backward compatible, I actually just tested running all our integration test of 3.5.x agains a mule core 3.4.0 and it worked. 
If you can avoid doing this it'll be better though, I can't guaranty that all Munit features will work properly running on a later version of Mule core. I don't yet have that level of interop testing.  

Cheers
